### ISSUE TITLE
Copiar progresos de la traducción en Español (España)

### ISSUE THREAD

**Issue by Niquito** [Ludeon/RimWorld-SpanishLatin#10]
Hola! Estuve revisando los archivos que faltan traducir y encontré que una gran parte de los mismo ya están traducidos en la versión española. Revisar cada caso para alterar los modismos llevaría mucho menos tiempo que el de tipear todo el contenido de nuevo, por éso pregunto:

¿Y si copiamos los progresos que hicieron en la traducción española **revisando cada párrafo**?

**Comment by Andres6936** [comment]
Me parece perfecto, sin embargo, el inconveniente como lo dices tú, son los modismos que se utilizan en las versiones distintas al Latino, hace mucho que no le dedico un poco de tiempo a las traducciones y vendría de manera estupenda una ayuda.
