### ISSUE TITLE
Encontrar traducción adecuada / Find the appropriate translation

### ISSUE THREAD

**Issue by Andres6936** [Ludeon/RimWorld-SpanishLatin#12]
Encontrar una traducción adecuada para las siguientes lineas.

https://github.com/Ludeon/RimWorld-SpanishLatin/blob/d2185c12261109fa014b17a21bcca375b96a3375/Keyed/Time.xml#L21-L24

**Comment by Andres6936** [comment]
Las traducciones originales son:

```xml
<QuadrumAprimay>Aprimay</QuadrumAprimay> 
<QuadrumJugust>Jugust</QuadrumJugust> 
<QuadrumSeptober>Septober</QuadrumSeptober> 
<QuadrumDecembary>Decembary</QuadrumDecembary> 
```

**Comment by Andres6936** [comment]
Encontré la relación que uso Tyan para cambiar las fechas:

Son las siguientes:

Aprimay: Equinoccio de Marzo
Jugust: Solsticio de Julio
Septober: Equinoccio de Septiembre
Decembary: Solsticio de Diciembre

De momento las Strings de las etiquetas quedaran así:

```xml
<QuadrumAprimay>Equinoccio Mayor</QuadrumAprimay>
<QuadrumJugust>Solsticio Mayor</QuadrumJugust>
<QuadrumSeptober>Equinoccio Menor</QuadrumSeptober>
<QuadrumDecembary>Solsticio Mayor</QuadrumDecembary>
```

**Comment by Andres6936** [comment]
Otro nombre al cual se le puede dar a Aprimay es **Vernal**.

**Comment by Andres6936** [comment]
Otro nombre al cual se le puede dar a Septober es **Otoñal**.

**Comment by Niquito** [comment]
String original | Referencia
Aprimay: April + May 
Jugust: July + August
Septober: September + October
Decembary: December + January

Traducción | Referencia
Abrimayo : Abril + Mayo
Juliosto : Julio + Agosto
Septobre : Septiembre + Octubre
Dicienero: Diciembre + Enero

**Comment by Andres6936** [comment]
@Niquito Qué te parece la idea de dejar la traducción como **Equinoccio de** y **Solsticio de**.

En lo personal me gusta esa traducción, aunque **Vernal** y **Otoñal** también son una buena opción.

**Comment by Niquito** [comment]
@Andres6936 Sinceramente también me gusta la traducción que sugerís, pero creo que nos estamos alejando de la intención original de los desarrolladores. 
Como puse en el comentario anterior, los nombres refieren a una mezcla entre dos meses y no a la posición del sol, o la estación en la que se encuentre. Por ende, creo que si quisiéramos traducirlo correctamente deberíamos jugar con los nombres como hicieron originalmente los desarrolladores.
No digo que se utilice textualmente lo que propuse yo, pero sí creo que la línea debería ir por ahí.

**Comment by Andres6936** [comment]
@Niquito Tienes toda la razón, seguiré investigando haber si logro encontrar una traducción adecuada.
Aunque el nombre de Vernal y Otoñal comprende los meses entre Abril y Mayo, y Septiembre y Octubre.
Faltaria encontrar una traducción para los meses de Diciembre Julio y Agosto, y Diciembre y Enero.

**Comment by Destiny609** [comment]
Buenas amigos, mi opinión sobre el tema es que deberíamos poner la traducción como lo dijo Niquito ya que si ponemos un sistema basado en la posición del sol seria muy complicado para las personas entenderlo para algunos ya que al hacer referencia al la posición del sol damos un pequeño lapso a las estaciones y pasa lo mismo con vernal y otoñal que hacen referencia a las estaciones y si tenemos en cuenta que en Rimworld las estaciones se distintan del hemisferio norte y el hemisferio sur y otras veces las cuadrículas no tienen estaciones, lo mas acertado que podríamos hacer es guiarnos por lo que ya esta puesto.

**Comment by Andres6936** [comment]
Sigue sin gustarme la idea, aunque si alguno de ustedes dos me propone una buena traducción combinando ambos meses la podría terminar aceptando, pero de momento quiero algo corto y comprensible.

**Comment by Destiny609** [comment]
Adelanto de lo que yo tiena pensado sobre los Quadrums, como sabran los Quadrums hacen referencia a los meses terrestres y son combinaciones de 2 meses y lo que estuve viendo es un poco de la historia de cada uno de los meses que hace referencia y no me acaban de convencer los nombres en latin por los cuales de les denomina y investigando un poco mas encontre unos cuantos calendarios los cuales serian los calendarios Incas, Hebreo e Egipcios los cuales hacen una mezcla de dos meses y podríamos utilizar unos nombres de alli, dejare otros comentarios con los nombres referentes a cada uno.

**Comment by Destiny609** [comment]
Calendario Hebreo
Aprimay: Iyar
Jugust: Av
Septober: Tishrei
Decembary: Tevet

**Comment by Destiny609** [comment]
**Calendario Egipcio**
- Aprimay: PaenJonsu
- Jugust: MesutRa
- Septober: PaenIpat
- Decembary: TaAabet

**Comment by Destiny609** [comment]
**Calendario Bahai**
- Aprimay: Jamál
- Jugust: Kalimát (este nombre es solo del mes de julio ya que no combinan julio y agosto)
- Septober: Mashíyyat
- Decembary: Sharaf

**Comment by Destiny609** [comment]
Habia leido que Tynan tuvo pensado utilizar los nombres de los números en latin, por lo cual podríamos utilizar esa idea si es que no se nos da de utilizar una traducción o un calendario de los que mencione anteriormente.

**Comment by Destiny609** [comment]
**Numeros en Latin(del 1 al 4)** 
- Unus
- Duo
- Tres
- Quattuor

**Comment by Destiny609** [comment]
**Una alternativa simple y origina** 
Se me ocurrió que podríamos mezclar la palabra "Quadrums" es son los meses en Rimworld y los nombres de los números en latin y por lo que tengo ahora esta entendible y en mi opinión seria una buena alternativa.

**Combinacion de Quadrums + Números en Latin** 
- Quadrums+Unus: Quadrunus
- Quadrums+Duo: Quadruo 
- Quadrums+Tres: Quadres
- Quadrums+Quatruor: Quattuor(En mi opinión este debería seguir sin mezclarse)

**Comment by Niquito** [comment]
Creo que nos estamos corriendo del eje, porque en vez de traducir el juego (que es lo que deberíamos hacer) estamos buscando nomenclaturas que nos gusten.
Sigo creyendo que la intención original de los desarrolladores al crear, por ejemplo, "Aprimay" es mezclar dos meses conocidos en una misma palabra (April + May). Si nuestra idea es traducir el juego al español latino, deberíamos de respetar ésa idea y limitarnos a traducirlo como corresponde. 
Si por el contrario, traducimos "Aprimay" como "Equinoccio Auadres de 3ra luna", es subjetivo determinar si es mejor o peor que el texto original... pero claramente no termina siendo traducir, sino interpretar lo que más nos guste.

O sea, si queremos traducir deberíamos de seguir una línea que se aferre objetivamente a lo que dice cada texto. De lo contrario, debería de crearse una derivación distinta para incluir ésas "mejoras o retoques" que no sean traducciones directas.

**Comment by Destiny609** [comment]
Tienes razón Niquito, vere una combinación de los meses, teniendo en cuenta como esta escrito en el ingles o vere como arreglo lo que ya habias propuesto

**Comment by Andres6936** [comment]
Con lo que respecta a las ideas que ha dado @Destiny609 me encantan, sobre todo me parece muy factible el uso del **Calendario Hebreo**, por otro lado, la alternativa que has sugerido de los Quadrums, no es factible, la palabra Quadrums hace uso de varios lapsos de tiempos en una sola palabra, eso significa que **Quadrums significa cualquier lapso de tiempo**, pero **en tu idea utilizas cuatro palabras para describir distintos lapsos de tiempo**.

Con lo que respecta a la opinión de @Niquito, en parte tiene razón y ahora más que nunca me estoy dando cuenta de que si seguimos nuestras propias traducciones e interpretaciones vamos a tener un problema.

Aprecio mucho el trabajo que ha hecho @Destiny609 hallando traducciones e interpretaciones que encajen con el significado, sin embargo a no ver mejor resultado, creo que deberíamos optar por escoger alguna de las sugerencias de @Destiny609.

**Comment by Destiny609** [comment]
Lo he estado pensando y pues esto fue lo que pude realizar.

- Aprimay: Abrimay
- Jugust: Jugost
- Septober: Septobre(Ya lo propuso Niquito)
- Decembary:Dicienero(Ya lo propuso Niquito)

**Comment by Andres6936** [comment]
Revisando las traducciones de otros repositorios (Exactamente las traducciones Rusas, China y China Simplificado) encontré que habían empleado el método original (traducido de manera similar a la que Tynan había usado), así que debo de admitirlo, estaba en un error tratando de encontrar una relación.

Si todos están de acuerdo usaremos las siguientes traducciones:

- Abrimay  (@Destiny609 )
- Jugost     (@Destiny609 )
- Septobre (@Niquito)
- Dicienero (@Niquito)

**Comment by Destiny609** [comment]
Pues entonces ya encontramos nuestra traducción para los Quadrums, puedes avisarme para cuando agregaremos la traducción?

**Comment by Andres6936** [comment]
**Cambios implementados**

_Cierro Discusión_
