### ISSUE TITLE
Review translations of Strings/Names/Animal_Female.txt

### ISSUE THREAD

**Issue by Andres6936** [Ludeon/RimWorld-SpanishLatin#13]
Revisar las traducciones del archivo **Strings/Names/Animal_Female.txt**

**Comment by Destiny609** [comment]
He estado revisando el archivo correspondiente y he notado que hay algunos nombres que no estan en su orden el cual seria por abecedario y estare corrigiendo esto mañana por la mañana y vere si hace falta alguno lo agregare.

**Comment by Destiny609** [comment]
Me acabo de dar cuenta que el orden esta bien ya que coincide con el original, el problema es que faltan nombres en el original hay 214 mientras en la traducción hay 156, esto lo estaré arreglando en el transcurso de dia.

**Comment by Andres6936** [comment]
@Destiny609, de echo, estaba usando el traductor [Deep](https://www.deepl.com/translator) para arreglar y corregir las cadenas, de echo como el archivo es muy largo y de poco relevancia para las traducciones lo que estaba realizando era corregir las erratas que se encontrasen.

Lo ideal es usar una herramienta que te facilite la ayuda en archivos como estos, ya que son largos y a veces molestos de traducir.

Te agradezco que hayas tomado la molestia de arreglar el archivo.

Etiquetearé a este **Issues** como de baja prioridad.

Gracias @Destiny609.

**Comment by Destiny609** [comment]
Esta bien @Andres6936  por ahora ya voy a mitad del trabajo, solo me falta rellenar los espacios que faltan y traducirlos.

**Comment by Destiny609** [comment]
**Esto es lo que pude hacer con los nombres, hay algunos que están en otro idiomas en el original los cuales pase a español y hay otros que no suenan tan bien pero son su traducción al español.(utilize algunos de los que ya estaban en la traducción hecha)**
Abby: Abi 
Akira: Akira 
Alexia: Alexia
Allegra: Alegre
Amber: Ambar
Anais: Anais
Anastacia: Anastacia
April: Abril
Ariel: Ariel
Athena: Athena
Aurora:  Aurora
Babette: Bebe
Babs: Babas
Babushka: Babushka
Bambina: Chica
Bella: Bella
Bella Donna: Doña Bella
Belle: Bel
Beulah: Bula
Bianca: Bianca
Bidget: Brigida
Blanche: Blanco
Blondie: Rubia
Blossom: Bolita
Brandy: Brandy
Brittabny: Britania 
Brunilda: Bruna
Buffy: Amada
Bugsy: Bugsi
Butterfly: Mariposa
Cedence: Cadencia
Calypso: Calipso
Carnation: Clavel
Carolina: Carolina
Cassidy: Gorgonia
Cassie: Casie
Cassandra: Casandra
Catalina: Catalina
Cha-Cha: Cha-cha
Charlotte: Carlota
Chelsea: Chelsea
Chiquita: Chiquita
Chloe: Colita
Chocolata: Chocolate
Circle: Redonda
Clementine: Clementina
Cleo: Cleo
Coquette: Coqueta
Corona: Corona
Cowgirl: Vaquita
Crystal: Cristal
Czarina: Harina
Daisy: Daisy
Dakota: Dakota
Damsel: Damisela
Daphne: Dafne
Dawn: Amanecer
Debutante: Principiante
Delilah: Delias
Desiree: Deseo
Didi: Didi
Dixye: Dixy
Doll: Muñeca
Dolly: Carrito
Dudette: Bizcocho
Elsa: Elsa
Elvira: Elvira
Emily: Emilia
Emma: Emma
Europa: Europa
Fantasia: Fantasia
Fifi: Fifi
Fleur: Flor
Flora: Flora
Geisha: Geisha
Georgia: Georgia
Gertrude: Gertrudis
Gidget: Gigante
Gigi: Gigi
Giselle: Giselle
Goldie: Patas de Oro
Goldilock: Candado de Oro
Gorda: Gorda
Grace: Grace
Gretel: Gretel 
Gwenevere: Severa
Haley: Haley
Heather: Brezal
Haven: Darcenas
Heidi: Heidi
Hilda: Hilda
Holly: Santurrona
Hope: Brinco
Iris: Iris 
Isabelle: Isabela
Isis: Isis
Ivy: Arena
Jasmine: Jasmin
Jemina: Jemina
Jezebel: Chasque
Joy: Satisfaccion
Juliet: Julia
Kiki: Kiki
Kiku: Kiku
Lancey: Puntilla
Lady: Princesa
Lavender: Lavanda
Leila: Leila
Lilith: Lili
Lira: Lira
Lola: Lola
Lolita: Lolita
Lolli: Loli
Lolly: Olly
Lulu: Lulu
Madame: Señora
Maggie: Margarita
Mamie: Mamita
Mandy: Mandy
Marigold: Mani de Oro
Mariyn: Marilin
Matilda: Matilda
May: Mayo 
Maya: Maya
Medusa: Medusa
Melody: Melodia
Minerva: Minerva
Minnie: Pequeña
Misha: Misha
Missie: Perdida
Mona: Mona
Mopsy: Mopsi
Moxie: Moxie
Mugsy: Mugsi
Nellie: Nelli
Nikita: Nikita
Nina: Nina
Noisette: Risitas
Nova: Nova
Novella: Novela
Nymph: Ninfa
Opal: Opalo
Ophelia: Ofelia
Paddy: Arrozito
Pandora: Pandora
Patsy: Patatas
Penelope: Penelope
Penny: Peny
Persephone: Persefona
Petite: Pequeña
Petulia: Petulia
Piper: Flauta
Pippi: Pipi
Polly: Corpulenta
Portia: Por Tia
Prima Donna: Prima Donna
Prissy: Prosa
Prudence: Prudencia
Pudguette: Pudin
Queen Bee: Reina Abeja
Queeny: Reina
Rhea: Rea
Rosarita: Rosa
Rosie: Rocio
Roxanne: Roxana
Roxy: Roxy
Ruby: Rubi
Sadie: Sadi
Sapphire: Safiro
Sassy: Traviesa
Savannah: Savana
Scarlet: Scarlet
Scintilla: Escayola
Sera: Sera
Sheba: Sheba
She-Devil: Diabla
Shelley: Leyenda
Shiva: Shiva
Sidney: Sidney
Sienna: Siena
Sierra: Sierra 
Sissy: Mriquita
Sonata: Sonata
Sophie: Sofia
Sorceress: Sorcera
Starlet: Estrella
Stella: Estela
Tamara: Tamara
Tara: Tara 
Tess: Tess
Tilly: Tediosa
Tineker: Juguetona 
Tootsie: Letal
Trixie: Trixi
Uma: Uma
Uriel: Uriel
Ursa: Ursa 
Ursula: Ursula
Valentina: Valentina
Venus: Venus
Verona: Verona
Violet: Violeta
Vixen: Arpia
Wanda: Wanda
Wilhelmina: Helena
Willow: Deber
Witch: Bruja
Xena: Xena
Yuma: Yuma
Zelda: Zelda
Zoe: Zoe
Zooey: Zeta

**Comment by Andres6936** [comment]
**Mis sugerencias y revisiones.**

Athena : Atenea
Czarina : Zarina
Daisy : Margarita
Dolly : Lola || Lolita  # Alguno de los dos es buena opción.
Gidget : Gidget         # No hallé una traducción adecuada.
Goldie : Goldie         # No hallé una traducción adecuada, Sin embargo es un nombre propio.
Goldilock : Ricitos
Hope : Esperanza        # Literalmente es 'esperanza', sin embargo podemos utilizarlo como nombre propio.
Ivy : Ivy
Jezebel : Jezabel       # Notesé la sutil diferencia.
Moxie : Moxi
Polly : Mary || Molly   # Polly es un sobrenombre para Mary, y es la derivación de otro sobrenombre para Mary, Molly.
Polly : Paulina         # Otra buena alternativa.
Portia : Portia         # Es un sobrenombre que se utiliza para describir a mujeres que son difíciles de tratar.
Prima Donna : Diva      # Traducción del italiano, es la primer mujer que canta en el inicio de un coro.
Pudguette : Pudin       # La traducción es correcta, solo me hace gracia resaltarla acá.

_@Destiny609 Haz hecho un trabajo impecable, te lo agradezco mucho._

**Comment by Destiny609** [comment]
Si, son buenas alternativas las que sugieres @Andres6936 podríamos hacer todos los cambios, pero ¿se pueden repetir nombres?, note que en Daisy pusiste también Margarita y en la traducción original hay un nombre que es Maggie y segun entiendo Maggie es Margarita.

**Comment by Andres6936** [comment]
Por supuesto que se pueden repetir, sin embargo en ese caso podemos utilizar una variante de Margarita en este caso Margaret.

**Comment by Destiny609** [comment]
Muy bien @Andres6936  lo estare anotando en mi cuaderno, ¿luego vemos como lo agregamos?

**Comment by Destiny609** [comment]
Se ha actualizado satisfactoriamente.
