### ISSUE TITLE
Review translations of Strings/Names/Animal_Male.txt

### ISSUE THREAD

**Issue by Andres6936** [Ludeon/RimWorld-SpanishLatin#14]
Revisar las traducciones de **Strings/Names/Animal_Male.txt**

**Comment by Destiny609** [comment]
Mañana comienzo con este Issue.

**Comment by Destiny609** [comment]
Comenzare ya con este issue, lo único  que falta son alguno nombres y corregiré si se presenta algún error, lo estaré terminando para hoy por la tarde.

**Comment by Destiny609** [comment]
**He tardado un poco, pero al final ya lo tengo**

Abel: Abel
Adonis: Donis
Aesop: Abrojo 
Ajax: Ajac
Aladdin: Aladin
Alastair: Alister
Aldo: Aldo
Ali Baba: Alibaba
Allegro: Alegre
Amos: Amo
Angus: Angus
Apollo: Apolo
Archie: Archie
Ares: Ares
Argus: Malo
Ari: Ari
Aristoteles: Aristoteles
Arty: Arti
Atlas: Atlas
Atticus: Aticus
Attila: Atila
Augustus: Augusto
Austin: Austin
Bacchus: Baco
Baldric: Baldrico
Baldwin: Balduino
Baldy: Calvito
Bambino: Chico
Barbarino: Barabarino
Barney: Barney
Bart: Batido
Bartholomew: Bartolomeo
Baxter: Baxter
Beau: Bea
Beauregard: Bonito
Beethoven: Betoven
Bellboy: Campanilla
Ben: Ben
Benjamin: Benjamin
Benji: Benji
Bianco: Bianco
Big Boy: Chicho Grande
Blotto: Manchas
Bob: Bob
Bogeyman: Coco
Bond: Vinculo
Boris: Boris
Boy: Muchacho
Bruno: Bruno
Brutus: Bruto
Bubba: Burbujas
Byron: Biron
Caesar: Cesar
Calvin: Calvin
Camus: Camus
Capone: Capo
Casanova: Casanova
Caspar: Caspar
Cassius: Casio
Cecil: Cecilio
Cecily: Cecilia
Chester: Chester
Chico: Muchacho
Cisco: Cisco
Clyde: Pinzas
Cody: Cody
Conan: Conan
Confucius: Confucion
Cory: Cori
Cowboy: Vaquero
Cyramo: Cyramo
Czar: Zar
Da Vinci: Da Vinci
Dan: Dan
Dude: Duda
Dudley: Pudin
Duncan: Duncan
Dylan: Dylan
Ebenezer: Nivel
Elias: Elias
Elmer: Mer
Elmo: Elmo
El Roy: El Rey
Elvis: Elvis
Emerson: Emerson
Enzo: Enzo
Errol: Errol
Felix: Felix
Ferdinand: Fernado
Figaro: Figaro
Finn: Finn
Fletch: Peludo
Flint: Piedra
Floy: Flojo
Frasier: Fraser
Freud: Feliz
Friar: Fray
Gatsby: Puertas
Gavin: Gavin
Gilligan: Gilligan
Gomer: Gomas
Gordo: Gordo
Groucho: Groucho
Grover: Cultivador
Gulliver: Guliver
Gunner: Tirador
Gunther: Pistolero
Gus: Gus
Guy: Tio
Halmet: Hojas
Handsome: Guapo
Hannibal: Anival
Hansel: Hansel
Harvey: Cosecha
Heathcliff: Seguridad
Hercules: Hercules
Herman: Hernan
Hermes: Hermes
Homeboy: Niño de Casa
Homer: Homero
Horace: Hora
Horatio: Horacio
Horus: Horus
Houdini: Judini
Huck: Ciervo
Hugo: Hugo
Humpherey: Zumbido
Hyde: Paramo
Icarus: Icaro
Ignatius: Ignacio
Igor: Igor
Jack: Jack
Jade: Jade
Jasper: Jasper
Jed: Jed
Jethro: Avion
Justus: Justo
Kobi: Kodi
Lad: Grava
Lancelot: Lancelot
Lazarus: Lazarus
Leo: Leo
Levi: Levi
Link: Link
Linus: Linus
Little Guy: Pequeño
Ludwig: Peluca
Macho: Macho
Malcom: Colmillos
Max: Max
Melvin: Melvin
Miles: Miles
Monk: Monje
Morris: Moris
Mortimer: Temporizador
Mozart: Mozart
Mozzie: Mozie
Nietzsche: Roblon
Niko: Niko
Newton: Newton
Noah: Noah
Oliver: Oliver
Ollie: Almeja
Orion: Orion
Oscar: Oscar
Othello: Otelo
Otis: Otis
Otto: Oto
Ozzie: Ozi
Paco: Paco
Paddington: Acolchado
Patton: Paton
Pavlo: Pablo
Perseus: Perseo
Petit: Menorcito
Pharaohn: Faraon
Popeye: Popeye
Quasimode: Cuasimodo
Quixote: Quijote
Ralph: Ralph
Ray: Ray
Rem: Recuerdo
Remy: Sobras
Reuben: Ruben
Rhett: Discurso
Riccky: Riky
Rocko: Rocko
Rocky: Roky
Rogan: Rogan
Romeo: Romeo
Roscue: Roscas
Rufus: Rufus
Rupert: Rupert
Salvatore: Salvador
Samsom: Samson
Scrooge: Escoba
Seymur: Symur
Shakespeare: Pera Agitada
Sherlock: Sherlock
Siegfried: Mejor Amigo
Sigmund: Sigmun
Sinbad: Sin Cama
Solomon: Salomon
Sorcerer: Brujo
Spike: Spike
Stetson: Ruidoso
Tarzan: Tarzan
Tinman: Hojalata
Toby: Toby
Tamba: Tamba
Tom-Tom: Tom-Tom
Tonto: Tonto
Ulysses: Ulises 
Valentino: Valentino
Van Gogh: Van Gogh
Voltarie: Voltarie
Waldo: Valla
Warlock: Hechisero
Wilbur: Wilbur
Wilfred: Wilfred
Wilson: Wilson
Wiseguy: Sabiondo
Wizard: Mago
Wolfgang: Lobo
Xanadu: Xanadu 
Xanthus: Xantu
Xavier: Javier
Xerxes: Jerjes
Zack: Zack
Zeke: Zeke
Zeus: Zeus
Zorro: Zorro

**Comment by Andres6936** [comment]
**Pendiente de revisión**

**Comment by Andres6936** [comment]
- Aristoteles : Aristóteles
- Bart : Bartolo || Barto **# Apodo de Bartholomew**
- Beauregard : Galán
- Blotto : Barney **# Referencia a los Simpsons, 'Blotto' es una persona que mantiene borracha.**
- Confucius : Confucio
- Ebenezer : Ebenezer
- Halmet : Halmet
- Handsome : Galán
- Hannibal : Aníbal
- Harvey : Harvey
- Heathcliff : Caballero **# Referencia a Cumbres Borrascosas.**
- Horace : Horacio
- Hike : Caminante **# Persona que camina mucho.**
- Hyde : Hyde
- Jethro : Jetro
- Lad : Muchacho
- Lazarus : Lázaro
- Lancelot : Lanzarote
- Linus : Leo
- Ludwig : Ludwig
- Malcom : Malcom
- Mortimer : Mickey
- Nietzsche : Nietzsche
- Ollie : Ollie
- Paddington : Paddington
- Patton : Patton
- Petit : Pequeño
- Rhett : Rhett
- Roscue : Ross
- Scrooge : Scrooge **# Persona tacaña.**
- Shakespeare : Shakespeare
- Siegfried : Coronel
- Sinbad : Simbad **# Notese la sútil diferencia.**
- Stetson : Stetson
- Warlock : Hechicero
- Wiseguy : Wiseguy
- Wizard : Genio || Mago || Hechicero
- Wolfgang : Wolfgang

**Comment by Andres6936** [comment]
Muchísimas gracia @Destiny609 por las traducciones.

**Comment by Destiny609** [comment]
De nada Andres para eso estamos.

**Comment by Destiny609** [comment]
Se ha actualizado satisfactoriamente.
