### ISSUE TITLE
Translate the lines 60-61-62/70-71-72 of DefInjected\IncidentDef\Incidents_Map_Misc

### ISSUE THREAD

**Issue by Destiny609** [Ludeon/RimWorld-SpanishLatin#17]
Estas son las lineas de 60-61-62
    <Aurora.label>aurora</Aurora.label>
    <Aurora.letterText>A beautiful aurora is lighting up the sky.\n\nThe undulating colors will boost the mood of anyone outside to see them, and make the night brighter.</Aurora.letterText>
    <Aurora.letterLabel>Aurora</Aurora.letterLabel>

Estas son las lineas de 70-71-72
    <Tornado.label>tornado</Tornado.label>
    <Tornado.letterText>A tornado has formed!\n\nIt will cut a path of destruction through the area.</Tornado.letterText>
    <Tornado.letterLabel>Tornado</Tornado.letterLabel>

**Comment by Destiny609** [comment]
Estaré poniendo aquí una traducción hecha.

**Comment by Destiny609** [comment]
<Aurora.label>Aurora Boreal</Aurora.label>
<Aurora.letterText>Una bella Aurora Boreal ilumina los cielos.\n\nLos colores ondulantes aumentaran el humor de cualquiera que este afuera para verlos, hará la noche mas brillante.</Aurora.letterText>
<Aurora.letterLabel>Aurora Boreal</Aurora.letterLabel>

**Comment by Destiny609** [comment]
<Tornado.label>Tornado</Tornado.label>
<Tornado.letterText>¡Se ha formado un tornado!\n\nDejara un camino de destrucción a su paso por el area.</Tornado.letterText>
<Tornado.letterLabel>Tornado</Tornado.letterLabel>

**Comment by Destiny609** [comment]
Solo necesito que lo acepten así lo implementare a la traducción.

**Comment by Andres6936** [comment]
Hay una cuantas faltas ortográficas.

* Deajara = Dejará
* area = área
* mas = más

Muchas gracias @Destiny609

**Comment by Destiny609** [comment]
He realizado los cambios cerrespondientes y gracias por las correcciones @Andres6936
