### ISSUE TITLE
Bug in the translate /Keyed/Incidents.xml

### ISSUE THREAD

**Issue by Destiny609** [Ludeon/RimWorld-SpanishLatin#19]
![bug](https://user-images.githubusercontent.com/34174168/33975220-f2743fec-e06b-11e7-84b4-2f3ec0caffbe.png)

**Creo que en estas linea estaría el Error**
  <AnElectricalConduit>un cable eléctrico</AnElectricalConduit>
  <ShortCircuit>Una falla en el/la {0} ha causado un corto circuito.\n\nLa totalidad de los {1} Wd de electricidad, que las baterías conectadas a esta red guardaban, se han descargado en la explosión.</ShortCircuit>
  <ShortCircuitWasLarge>Esta gran cantidad de energía ha creado una explosión de tamaño considerable.</ShortCircuitWasLarge>
  <ShortCircuitWasHuge>Ha sido una explosión enorme. Increíble.</ShortCircuitWasHuge>

**Comment by Destiny609** [comment]
<AnElectricalConduit>un cable eléctrico</AnElectricalConduit>
  <ShortCircuit>Una falla en el/la {0} ha causado un corto circuito.\n\nLa totalidad de los {1} Wd de electricidad, que las baterías conectadas a esta red guardaban, se han descargado en la explosión.</ShortCircuit>
  <ShortCircuitWasLarge>Esta gran cantidad de energía ha creado una explosión de tamaño considerable.</ShortCircuitWasLarge>
  <ShortCircuitWasHuge>Ha sido una explosión enorme. Increíble.</ShortCircuitWasHuge>

**Comment by Andres6936** [comment]
Investigare en el repositorio original.

**Comment by Destiny609** [comment]
Tranquilo @Andres6936 ya tengo la solución.

**Comment by Destiny609** [comment]
La estare pasando aqui en unos instantes

**Comment by Andres6936** [comment]
Ya he echo yo la solución.

**El Commit se ha enviado.**

**Comment by Andres6936** [comment]
El error se origino porque las etiquetas no contenían las cadenas <**String**> correctas, además de que existían dos etiquetas más que no habían sido incluidas.

**Comment by Destiny609** [comment]
**Bueno he notado que en la vercion original tampoco aparecian las lineas de <shortcircuitstarfire>/<shortcircuitwaslarger>/shortcircuitwashuge>(el ultimo lo añadi a la solucion)**

  <AnElectricalConduit>Un cable electrico</AnElectricalConduit>
  <ShortCircuit>Una Falla en {0} ha causado un cortocircuito.</ShortCircuit>
  <ShortCircuitDischargedEnergy>La totalidad de {0} Wd de energia que las baterias conectadas a esta red guardaban se ha descargado en una explosion de energia con un tamaño considerable.</ShortCircuitDischargedEnergy>
  <ShortCircuitWasHuge>Ha sido una explosion enorme, Increible!.</ShortCircuitWasHuge>

**Comment by Destiny609** [comment]
Esta Bien @Andres6936 lo estare testeando mas tarde.

**Comment by Destiny609** [comment]
![solucionado](https://user-images.githubusercontent.com/34174168/34006122-f62404ea-e0db-11e7-996f-3b066f4a1435.png)

Ya esta correctamente, gracias 2 @Andres6936 , cierro este issue.
