### ISSUE TITLE
Bug(este bug nose donde se podría ubicar)

### ISSUE THREAD

**Issue by Destiny609** [Ludeon/RimWorld-SpanishLatin#20]
![bug](https://user-images.githubusercontent.com/34174168/34060054-d21be01e-e1c0-11e7-89aa-d0b9a62fe2e6.png)

**He notado que en otras traducciones paso esto al principio, pero creo que ya lo han solucionado y no encuentro el origen del error.**

**Comment by Andres6936** [comment]
@Destiny609 Buscaré el error, pronto tendré una solución.

**Comment by Destiny609** [comment]
@Andres6936 muchas gracias compañero.

**Comment by mora145** [comment]
Pareciese un problema que va mas allá de las traducciones.

**Comment by Destiny609** [comment]
Si yo también lo había pensado pero crei que se le podía dar algun arreglo.
