### ISSUE TITLE
Translate \DefInjected\InspirationDef/Inspirations

### ISSUE THREAD

**Issue by Destiny609** [Ludeon/RimWorld-SpanishLatin#21]
Traduciré estas lineas en los siguientes días.

**Comment by mora145** [comment]
Avisame si traduciras esto.

**Comment by Destiny609** [comment]
@mora145 en eso estoy compañero.

**Comment by Destiny609** [comment]
Terminado y probado, todo funciona correctamente, cierro este issue.
