### ISSUE TITLE
Activo

### ISSUE THREAD

**Issue by mora145** [Ludeon/RimWorld-SpanishLatin#22]
Estaré trabajando de nuevo en las traducciones. Por favor cuenten conmigo. Asi mismo los invito a darme una mano en la traduccion del MOD pack Hardcore-SK.

Saludos

**Comment by Destiny609** [comment]
Enhorabuena @mora145, ¿como vas compañero?, yo soy el nuevo y pues podria ayudarte también con las traducciones del Mod pack del cual hablas, también seria de gran ayuda que agregarás con Andres las nuevas lineas que faltan, desde ya un saludo.

**Comment by mora145** [comment]
Todo bien por aquí, amigo. Solo si tienes tiempo, aquí dejo el link de Mod Pack: https://github.com/skyarkhangel/Hardcore-SK

Bien, supongo que estas usando el RimTrans para pasar todo lo nuevo de la A18, no?

**Comment by Destiny609** [comment]
Lo estaré viendo en el transcurso del dia, yo utilizo Atom y Notepad++ para hacer los cambios en los archivos que tengo de la traducción luego los pruebo y si todo funciona correctamente lo subo.

**Comment by mora145** [comment]
Ok, al referirte a las "nuevas lineas", supongo que hablas de la A18 ¿no?

**Comment by Destiny609** [comment]
Si, a eso me refiero, veras que yo puedo traducirlo y demas pero habia notado que faltaban "lineas"(No se como llamarlo) de la B18 y entonces seria bueno que la agregaras junto con Andres ya que a mi se me complicaría, y yo las estaré traduciendo en el transcurso de la semana, por ahora estoy en las inspiraciónes o motivaciones.

**Comment by mora145** [comment]
Estuve en un tiempo en contacto con el responsable de las traducciones, anterior a ti. Creo que le platee a él sobre pasar las traducciones mediante el RimTrans, debido a lo facil de usar y lo rápido localiza los cambios. Todas las demás idiomas lo usan para hacer tan rápido los cambios. ¿Podrías darle una revisada a ese software?

**Comment by Destiny609** [comment]
Creo que ya lo había visto pero si no le falla la memoria esta todo en un idioma Asiatico.

**Comment by mora145** [comment]
En ingles también. En un momento subo por aquí un .rar con todas las traducciones generadas, así le hechas un vistazo.

**Comment by Destiny609** [comment]
Te lo agradecería mucho, asi podré familiarizarme con el software.

**Comment by mora145** [comment]
Listo 

http://www.mediafire.com/file/qdc4ad22o9qgu08/SpanishLatin_RimTrans.rar

Creo que si se lo habían pasado con anterioridad. Aunque entre lineas sigue viéndose código nuevo (Que falta aun por traducir). No se si es de la A17 o de la B18, recién salida. Lo cierto es que entre las lineas de código podrás encontrar aquellas las faltan por traducir (Las reconoces porque están en ingles)... mas abajo podrás ver a veces, lineas comentadas, esas son las que no se les encontró vinculo alguno con las Def's, o a las cuales se les cambió el nombre de label. 

No se si hay archivos nuevos. En todo caso, aquellos que hayan sido creados, son porque en las Def's originales se creó igualmente. Si quieres puedes revisar por ejemplo las traducciones de los Rusos, y compararlas.

**Comment by mora145** [comment]
Y si, si lo habían pasado con anterioridad (Aunque no quiere decir que lo hayan hecho hace poco). Creo que me equivoqué entre Spanish Latin y Spanish... este ultimo faltaba por pasarle el RimTrans.

**Comment by Destiny609** [comment]
Pues esta bien Mora, lo estaré viendo y gracias por el url.

**Comment by Andres6936** [comment]
Igualmente es una buena idea usar la herramienta de traducción de RimTrans, hace un mes envié un **Pull** con una traducción al español  de la interfaz, pruebenlo. Ayuda a avanzar mucho.

Sin embargo recuerden, necesitan el sistema operativo Windows para usarlo.

**Comment by mora145** [comment]
Hablas del generador que siempre se usa o hay algo mas? No lo conozco. Estuve viendo uno que estaba integrado con la API de google traslator, pero era de Ingles a Chino

**Comment by Andres6936** [comment]
No, RimTrans es un programa para traducir especialmente las cadenas de los archivos de RimWorld, el generador es otra herramienta aparte, es más hay un repositorio donde suben las cadenas actualizadas, el enlace esta en la Wiki.

**Comment by mora145** [comment]
No logro entenderte. Con RimTrans si se generan las cadenas de archivos, pero como tal, el no traduce ni ayuda a traducir. Solo coloca las nuevas cadenas y uno hace el trabajo. 

Estuve viendo este, que si ayuda a traducir, pero como dije, de Ingles a Chino solamente. 
https://github.com/inkitter/RimTrans/releases

**Comment by Andres6936** [comment]
Espero no haberlo enredado más, Si es exactamente lo que dices @mora145, no ayuda a traducir, pero si ayuda a añadir las etiquetas y las cadenas más fácil para su posterior traducción.
