### ISSUE TITLE
RimWorld-SpanishLatin/Backstories/

### ISSUE THREAD

**Issue by mora145** [Ludeon/RimWorld-SpanishLatin#27]
Estaré traduciendo las historias de los personajes.

**Comment by mora145** [comment]
@Andres6936 ¿me podrías echar una mano con las revisiones? :)

**Comment by Andres6936** [comment]
Disculpen la demorá, son vísperas de navidad y es de suponer que ustedes al igual que yo deben de estar ocupados.

Si por supuesto.

**Comment by Destiny609** [comment]
@Andres6936 , @mora145 les quería avisar que bo estare actualizando los archivos en esta semana ya que estoy en la casa de mi abuela pero igualmente estare traduciendo lo que tengo pendiente y apenas tenga una conexión estable hare los commit.

**Comment by mora145** [comment]
Tranquilo @Destiny609 
@Andres6936 cuando puedas claro. 

Saludos. Felices navidades.
