### ISSUE TITLE
Hola, soy nuevo.

### ISSUE THREAD

**Issue by Irioto** [Ludeon/RimWorld-SpanishLatin#37]
Como dice el titulo soy nuevo en esto y me gustaria aprender como es trabajar en equipo via web, Tambien me gustaria ayudar, si se precisa algo madenme un msg o algo.

Discord: Irioto#0746

**Comment by Fercho191** [comment]
https://github.com/Ludeon/RimWorld-SpanishLatin/issues/38#issuecomment-388180886 😄
