### ISSUE TITLE
Buenas

### ISSUE THREAD

**Issue by MartEsc** [Ludeon/RimWorld-SpanishLatin#38]
Buenas, mil disculpas por la molestia, soy nuevo en github y la verdad es que me gustaría dar una mano pero todavía no me manejo muy bien con esta pagina jaja, queria consultar como era para empezar a trabajar con las traducciones, supongo que tengo que hacer un branch de master, empezar a trabajar y hacer una pull request,pero no estoy seguro y no quiero causar problemas asi que preferí hacer este issue para preguntarles como es jaja.
Gracias de antemano y mil disculpas de nuevo por la molestia.
Cualquier cosa les dejo mi Discord si prefieren comunicarse por ahi y mi mail.
Gmail: escowichmartin@gmail.com
Discord: EpicBaron#6576

**Comment by Fercho191** [comment]
Una de mas manera para colaborar con cualquier repositorio de Github es la siguiente

- Has fork de este proyecto (Te creara una copia del proyecto en tu github personal)
- clona el proyecto forked (El tuyo)
- Cuando lo tengas en local, añade un nuevo remoto desde git (Revisa la documentacion de git para ver como agregar un remoto a tu local) con la direccion de este proyecto, el original
- Trabaja en tu proyecto local (Siempre haciendo fetch desde el repo original para que estes al dia)
- Cuando tengas cambios que agregar, genera el pull request para unir los cambios de tu repositorio (el forked)  con el original

Sinceramente espero haberme hecho entender.. Si me falto algo, que alguien me corrija
