### ISSUE TITLE
Historias inexistentes

### ISSUE THREAD

**Issue by Fercho191** [Ludeon/RimWorld-SpanishLatin#4]
Hola! quiero preguntar sobre algo en el archivo [backstories.xml](https://github.com/Ludeon/RimWorld-SpanishLatin/blob/master/Backstories/Backstories.xml)

Estoy haciendo pruebas y me encontré con esto.
![backtories](https://cloud.githubusercontent.com/assets/13698504/26526462/f10344d8-4349-11e7-8640-a3dc90a0ed9c.png)

Esos transfondos no los encuentro en el archivo antes mencionados.

¿Existe una regla para crear las etiquetas de ese xml?
Como por ejemplo esta:
```XML
<GameDeveloper59>
	<title>Desarrollador de juegos</title>
	<titleShort>Desarrollador</titleShort>
	<desc>NAME era un desarrollador de juegos independiente. Después de un éxito temprano, la carrera de NAME rápidamente se degeneró en un circo de ideas equivocadas, los tratos salieron mal, y las acrobacias de PR desesperadas y fallidas.</desc>
</GameDeveloper59>
```

Crear algo del estilo:
```XML
<MidworldCadet¿?>
	...
</MidworldCadet¿?>
```

**Comment by Andres6936** [comment]
Eso sucede cuando el archivo **XML** no se actualiza de la forma correcta.

Lo que deberías hacer es buscar el archivo XML original (La version en inglés) y buscar dentro de ese archivo el **String** (_Midworld cadet o cualquier otra String que necesites traducir_) cuando la encuentres, también encontraras la etiqueta original, simplemente copia la etiqueta, pega la etiqueta en el archivo que vas a traducir (en este caso [backstories.xml](https://github.com/Ludeon/RimWorld-SpanishLatin/blob/master/Backstories/Backstories.xml)) y por ultimo traduce el texto.

Disculpa la explicación tan ineficiente.
Déjame busco las etiquetas y te ahorro el trabajo en parte.

**Comment by Andres6936** [comment]
El repositorio con el Idioma ingles original se encuentra aquí: [backstories.xml](https://github.com/RimWorld-zh/RimWorld-English/blob/master/Backstories/Backstories.xml)

**Comment by Fercho191** [comment]
@Andres6936 No fue una explicacion deficiente, entendí el punto :D vale gracias!
