### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by Destiny609** [Ludeon/RimWorld-SpanishLatin#40]
\SpanishLatin\Keyed\Time

 24 <Born>Nacimiento: {0} {1} {2}</Born>

¿Lo borramos o lo dejamos así hasta que se solucione?

**Comment by Etaglibash** [comment]
Observando el archivo en inglés me di cuenta que sólo tiene el {0}.
Borrando el {1} y el {2} se arregla, ya lo comprobé.

**Comment by Destiny609** [comment]
Muchas gracias colega.
