### ISSUE TITLE
DefInjected\RulePackDef

### ISSUE THREAD

**Issue by Destiny609** [Ludeon/RimWorld-SpanishLatin#42]
Quería dejar este issue por aquí para hacer recordatorio de lo que esta faltando.

**Comment by Etaglibash** [comment]
Cómo ves la creación de nombres de facción y de toponímicos? Hay algo que quisieras cambiar?

**Comment by Destiny609** [comment]
Supongo que esta bien colega..

**Comment by Etaglibash** [comment]
Voy a meterme de lleno a lo del rulepack, me gusta mucho jugar con ese código.
Cualquier sugerencia se acepta.

**Comment by SystemTechTraslate** [comment]
Yo me quiero unir a la traduccion ?
