### ISSUE TITLE
Nodos en las Rules e interacciones

### ISSUE THREAD

**Issue by mora145** [Ludeon/RimWorld-SpanishLatin#45]
Saludos amigos. @Destiny609 @Etaglibash  

Según me explicaron los coder's de Rimworld; para la versión 1.0 ya se podrán usar nodos. Sé que aun en el RimTrans no se actualiza esta característica, por lo que la forma en la que deberemos aplicar los nodos luego de pasar el RimTrans será mediante expresiones regulares, y usando el NotePad++ para reemplazar: 

**Dejo la forma:**

Esto: `[ \t]*<([^<>]+rulesStrings)\.0>([^<]+)<\/([^<>]+)>`
por esto: `\t<$1>#addclosetag\n\t<$1.0>$2</$3>`

Esto: `[ \t]*<([^<>]+rulesStrings)\.[0-9]+>([^<]+)<\/([^<>]+)>`
por esto: `\t\t<li>$2</li>`

Y esto: `(?s)<([^<>]+rulesStrings)>#addclosetag(((?!(<[^\/](?!(i>)))).)*)</li>`
por esto: `<$1>$2</li>\n\t</$1>`

Espero podamos terminar pronto lo que falta de las Rules, que es lo que más se complica. Feliz dia.

**Comment by mora145** [comment]
[RimWorld 1.0 Translation Improvements](https://ludeon.com/forums/index.php?topic=41942.msg412629)

**Comment by Etaglibash** [comment]
Ok. Las listas nuevas se ven mas compactas y limpias, pero supongo que no es obligatorio.
Todo lo que traduzco lo reviso en mi propio juego y funciona en el formato "viejo".

Mora, vas a cambiar todos los formatos de todos los archivos?

**Comment by mora145** [comment]
Asi es. Esto fue aplicado en primer momento por los mismos codeadores de Rimworld cuando pasamos a la 1.0. 

> Mora, vas a cambiar todos los formatos de todos los archivos?
A que te refieres? a los nodos? Si, ya eso se hizo.

**Comment by colo13verdadeo** [comment]
Sigue habiendo error?

**Comment by zerstrick** [comment]
La versión actual del juego ha dejado obsoleto el uso de esta guía, doy por terminado este tema.
