### ISSUE TITLE
--------------------UNETE AL GRUPO---------------------

### ISSUE THREAD

**Issue by mora145** [Ludeon/RimWorld-SpanishLatin#46]
**Saludo traductores, ayudantes o espectadores** @Destiny609 @Andres6936 @Etaglibash 

Se les extiende formalmente la invitación al grupo de Discord. La idea es unir los dos "Español" en un solo grupo. También para formar un lugar de ayuda entre nosotros mismos y documentar cualquier duda o problema que veamos en el camino; ademas, de: ¿por qué no?, bromear un rato.

_Espero podamos integrarnos más como grupo y compartir nuestros conocimientos._
Besos, se les quiere mucho :*

[Grupo Discord - Traductores Español/Español Latino](https://discord.gg/sJqMbRD)

**Comment by Etaglibash** [comment]
Invitación no válida, dice...

**Comment by mora145** [comment]
prueba con esta https://discord.gg/KF5cqmD

**Comment by mora145** [comment]
@GoldenMaur1 Saludos. Puedes unirte al grupo. Por alli podremos conversar amenamente. Te dejo el link: 
https://discord.gg/sJqMbRD
