### ISSUE TITLE
Backstories

### ISSUE THREAD

**Issue by mora145** [Ludeon/RimWorld-SpanishLatin#48]
Hi @isonil . 

You know? I've been looking for the latest Backstories, and I can't get them in English, updated. You know where I can get them? 
---
Hola. 

Sabes? He estado buscando las ultimas Backstories, y no las logro conseguir en ingles, actualizadas. ¿Tu sabes de donde puedo sacarlas?

**Comment by isonil** [comment]
@mora145 Hi, this used to be a bit difficult in the past, but now thanks to the new translation files cleaning tool it should be much easier. You can simply use the "Cleanup translation files" tool in the main menu and it will automatically add all missing backstories with TODO placeholders.
