### ISSUE TITLE
Presentación

### ISSUE THREAD

**Issue by GoldenMaur1** [Ludeon/RimWorld-SpanishLatin#49]
Quizás me hayan notado ya hacer unos mínimos cambios, pero me presento, soy **Goldenmauri**, estoy para ayudar en la traducción ya que mientras jugaba noté errores en la traducción, soy bueno con el inglés, por donde debería empezar?

**Comment by Andres6936** [comment]
Bienvenido **Goldenmauri**, mucho gusto tener nuevas caras por acá, referente a su pregunta, empieza por los lugares donde creas haber visto los errores, principalmente los **DefInjected** que son las cadenas principales de RimWorld, los **Backstories** son largos y tediosos, sin embargo, si puede realizar mejoras ahí sería perfecto.

Gracias nuevamente.
