### ISSUE TITLE
Errores en Backstories.xml

### ISSUE THREAD

**Issue by Runanegra** [Ludeon/RimWorld-SpanishLatin#50]
Encontré unos pequeños errores en backstories.xml. Saltaron al usar EdB Prepare Carefully pero daran igualmente error en las descripciones de las historias si aparecen en vanilla

Estos errores aparecen en algunos [PAWN_nameDef] que se han cambiado por error a [PAWN_nombreDef] lo mismo ocurre con [PAWN_possessive] que tambien se lo tradujo como [PAWN_possesivo]

Para PAWN_nameDef los errores aparecen en las lineas:

258
https://github.com/Ludeon/RimWorld-SpanishLatin/blob/6cb11b4649e8c91fa12938abe67d12fd671108c4/Backstories/Backstories.xml#L258
438
https://github.com/Ludeon/RimWorld-SpanishLatin/blob/6cb11b4649e8c91fa12938abe67d12fd671108c4/Backstories/Backstories.xml#L438
1185
https://github.com/Ludeon/RimWorld-SpanishLatin/blob/6cb11b4649e8c91fa12938abe67d12fd671108c4/Backstories/Backstories.xml#L1185
2391
https://github.com/Ludeon/RimWorld-SpanishLatin/blob/6cb11b4649e8c91fa12938abe67d12fd671108c4/Backstories/Backstories.xml#L2391
2454
https://github.com/Ludeon/RimWorld-SpanishLatin/blob/6cb11b4649e8c91fa12938abe67d12fd671108c4/Backstories/Backstories.xml#L2454
3849
https://github.com/Ludeon/RimWorld-SpanishLatin/blob/6cb11b4649e8c91fa12938abe67d12fd671108c4/Backstories/Backstories.xml#L3849

Para PAWN_possessive solo aparece en una linea:

4947
https://github.com/Ludeon/RimWorld-SpanishLatin/blob/6cb11b4649e8c91fa12938abe67d12fd671108c4/Backstories/Backstories.xml#L4947

Creo que no hay mas.

Lo mismo ocurre en la otra traducción.

Algo que me llamo la atención es el guion que antecede al comienzo del comentario de la linea 4. Mi conocimiento sobre xml no es que sea mucho pero no creo que le haga gracia al interprete de xml ese caracter... Tampoco es que vea que salte un error o advertencia pero creo que seria mejor quitarlo o meterlo dentro del comentario.

Saludos

**Comment by zerstrick** [comment]
Doy por cerrado este reporte de errores, pues todos han sido revisados y corregidos.
