### ISSUE TITLE
Saludos

### ISSUE THREAD

**Issue by mora145** [Ludeon/RimWorld-SpanishLatin#70]
Saludos amigos.
Hay algún problema con las strings? Cambiaron?

**Comment by Andres6936** [comment]
Hola @mora145 , Si, @zerstrick ha estado trabajando en mejorar las traducciones y arreglar errores con el formato y fallas en las etiquetas.

**Comment by mora145** [comment]
Excelente. Ya le pasaron el Rimtrans, supongo.

**Comment by Andres6936** [comment]
Quién realmente debería responder a esa pregunta debe de ser @zerstrick , quien es la persona que esta a cargo actualmente.

**Comment by zerstrick** [comment]
Hola, @mora145, @Andres6936   yo cloné el repositorio que habían subido con la 1.1 pero no recuerdo haber usado el  Rimtrans, actualmente tengo problemas con algunas quest que no entiendo su estructura porque me dan error, especialmente la última que agregaron para promover rangos, de resto acomodé el ruleck packs de arte y estaba trabajando en los otro ruleckpaks cuando sacaron la 1.2 y dejé eso de lado mientras trato de resolver lo de las quest, pero mientras doy con esa solución he seguido trabajando en la optimización de las oraciones para definir bien entre masculino y femenino, casi nunca abro mi correo que es cuando veo que han escrito por aquí, soy más activo en el discord, por allá me escribió Destiny pero empezó a trabajar y solo compartimos saludos.

**Comment by mora145** [comment]
@zerstrick Gracias por tu trabajo hermano. Creo que lo de las etiquetas desactualizadas se puede resolver rápidamente usando el Rimtrans. Le diré a Destiny que le dé una pasada (yo ahora no tengo instalado el Rimworld), pero puedo ayudar a traducir los faltantes y a acomodar las rules que son algo complicadas. 
Esperaré por @Destiny609 a ver que nos dice.

**Comment by zerstrick** [comment]
@mora145 Realmente no queda mucho por traducir, por mejorar si, pero por traducir la verdad es que no mucho, las reglas son complicadas pero son sencillas una vez entiendes el árbol de nombres, yo cree y separe varias palabras en el apartado strings para poder hacer distinción de sexo, porque antes todo lo coordinaban con el masculino, si me dices donde debo leer o me explicas de que va eso del Rimtrans lo puedo usar sin ningún problema, porque me tomé la tarea de ir revisando archivo por archivo del toda la traducción, hay varias cosas que tengo pendiente por modificar porque no se ven bien en los menús pero eso serán los detalles finales, ya por lo menos el menú principal de opciones quedó bien ya que no hay palabras que sobresalgan de los limites que tenia ludeon, pero hay otros menú donde no se lee bien lo que dice y se pierde uno que otro icono como es el caso de las políticas de drogas y la "hoja humeante enrollada" que es un nombre muy largo y luego no sale el símbolo 'i' que da la descripción, para cuando cree esas mejoras primero las dejaré en el segundo branch que cree antes de hacer un merge y que quedé de forma definitiva en el juego, Saludos.

**Comment by mora145** [comment]
Que bueno por eso entonces. Pensé que faltaba mucho más. Puedo darle una revisada completa al Repositorio a ver que hay que cambiar o arreglar. También es bueno usar la herramienta de búsqueda de errores a ver que hay. La puedes encontrar en el menú principal de Rimworld. Te generará un archivo de texto con los errores que puedan haber, o traducciones faltantes. 
El rimatrans es solo un actualizador de etiquetas/lineas de traducción, aunque no sé si está actualizado a los recientes cambios de Rimworld, de igual es bueno probar. Puedes encontrar informacion en https://github.com/Ludeon/RimWorld-SpanishLatin/issues/47
Al respecto de los nombres largos, cuando no encuentres una forma "rápida" de reducir el texto, me avisas, creo que hay una forma de usar una etiqueta que reduce un poco el tamaño del texto, ahora no recuerdo como era, pero puedo buscarla si la necesitas.

**Comment by zerstrick** [comment]
¡Oh! eso de la etiqueta reductora no lo sabía, y descuida que siempre que hay una actualización lo primero que hago es pasar las herramientas propias del juego, primero la que actualiza y luego la de reporte. Voy a revisar eso que me pasaste, gracias.
