### ISSUE TITLE
Backstories "Nombres de mundos"

### ISSUE THREAD

**Issue by mora145** [Ludeon/RimWorld-SpanishLatin#71]
Saludos chicos. 

Estuve revisando algunas backstories, y me dí cuenta que se están usando los términos "**Rimworlds**", "**Industrialworlds**", "**Urbworlds**" y "**Glitterworlds**" para referirse a lo que se sabe son otros planetas, con características sociales/económicas diferentes. 

Se supone que "**Rimworld**" se refiere a una zona (en este caso) un planeta... algo así como _fronterizo_, o del _borde_ lo que se podría inquirir, el _universo del juego_. 
Las características obviamente son lo salvaje del planeta, y poco habitado, algunos colonos que tratan de tomar el planeta, criminales que huyen de la ley y las frecuentes invasiones extraterrestres de los Mecanoides.
En este caso, para Rimworld, sugiero la traducción literal: "Mundos del Borde", aunque también se pueden usar otros como "Mundos fronterizos", "Planetas exteriores", "Planetas del Borde", etc. 

Otro que aparece es "**Glitterworlds**", el significado literal es "Mundos Brillantes". Son planetas que se suponen desarrollados, es de donde vienen las medicinas más caras, y las buenas armas, además de tener una economía muy fuerte, buenos sistemas de salud, nada de sobrepoblación, delincuencia y demás. Cuidan la naturaleza y su planeta en general. 
Por otro lado son muy dados al orden, el estudio, y también tienen una fuerza militar implacable. Para estos propongo también la traducción literal "Mundos Brillantes". Pero también podrían usarse algunos como "Tecno Mundos", "BrilloMundos", o cosas parecidas que denotan desarrollo. 

Los "**Urbworlds**" ya está traducido como "Mundos Urbanos". Son mundos donde reina el crimen organizado, las mafias, la prostitución y demás crímenes. Hay bandas de pandilleros, drogas, corrupción y demás. Un planeta entero sumido en el crimen. Podríamos mejorar esta traducción, ya que "mundos urbanos" podría referirse a varias cosas en nuestra lengua. 

El último y menos frecuente en la traducción es "**Industrialworlds**". Ya está traducido como "Mundos Industriales". Se supone son mundos con sobrepoblación, mucha industria contaminante, falta de alimento, suciedad, trata de personas, esclavismo. Son mundos fuertes económicamente, pero también muy pobres. La industria manufacturera es la más prominente allí. Bueno, estos están traducidos como "Mundos Industriales" Igual si se quiere se puede buscar alguna mejor traducción. 

Extra a estos, creo que están los "Mundos Colmena" "Hive worlds". Pero serían mas sociedades que completamente o en parte se agruparon y usaron tecnología para crear mentes "colmenas". Ya sean los mismos Mecanoides, Insectos, o humanos. Se menciona muy poco y algunos de los colonos que están en las historias han salido pitando de esos mundos sin explicar mucho de ellos. 

Bueno, avisenme lo que creen para arreglar esto. 
Saludos.

**Comment by zerstrick** [comment]
Hola, sí, yo hice el cambio para mantener la semántica de los nombres originales de estos mundos sin usar una traducción, esto para que cuando se hable de rimworld que es el nombre del juego las personas ya sean consiente de que se trata de lugares como bien mencionas pero sin que se pierda el sentido al traducir, toda la documentación oficial de esos mundos la encontré  [aquí ](https://docs.google.com/document/d/1fUO3KKbAbTxMP1lqphnnodY0NPoOVblCUkDw-54MDUc/pub ) al ser un lector de comics uno aprende que hay ciertas cosas que no deben ser traducidas, en este caso el nombre de los mundos fue algo que consulté en mi discord y la mayoría estuvo de acuerdo con eso.

**Comment by mora145** [comment]
Es bueno que leas comics, pero en este caso, no se está "nombrando" esos mundos; sino que tal término se está correspondiendo al 'tipo' socialmente hablando, dentro del cual se agrupa.
Y debido a que el tipo de planeta/sociedad equivale a una característica propia del mundo, debe traducirse. 
Es diferente que si por ejemplo X planeta se nombrara, "**PlanetaX**"; allí ya corresponde dejarlo sin traducción. Pero si se menciona el tipo de planeta por ejemplo "exoplanet", entonces tendrías que traducirlo por "exoplaneta" debido a que es una característica y no un nombre propio. 
Aquí otra frase de ejemplo: "The planet '**JulissaPrime**' is '**exoplanet**' class and its vegetation is of '**tundra**' type."
Solo corresponde dejar tal cual el nombre que es "JulissPrime", por ser un nombre propio.

Por otro lado, si te fijas en las demás traducciones, la mayoría han traducido tales términos.

Si quieres invita a los chicos del Discord a que se pasen por aquí y den sus opiniones

**Comment by zerstrick** [comment]
Entiendo muy bien tu punto, sin embargo muchos de los títulos de los trasfondo incluyen estos nombres la traducción de ellos no da para poderlos incluir ya que en la pantalla de selección de personaje no lo permite queda el nombre entrecortado, la adaptación de nombres en inglés al español y su posterior conservación tampoco es algo nuevo, tenemos palabras como airbag, jet pack, etc. Una de las cosas que deje claro en el discord fue precisamente que yo iba a crear una especie de wiki personal, así también práctico el diseño de páginas web para darle sentido a esos términos describiendo a qué hacen referencia, de igual forma el juego en sí mismo no te explica que son esos mundos, debes buscar fuera de este para saber que son, un fallo a mi parecer por parte de Ludeon cuando decidieron incluirlos, en cuanto a decirle a los miembros del discord que se unan a este debate es más complicado por el hecho de que deben pedir permiso y enviar un correo para tener acceso a estos repositorios y si no es así igual veo más conveniente el que tú te unas a nuestros discord ya que de ese modo es mucho más fácil para todos. 

En lo particular sigo creyendo que usar los nombres en inglés para hacer referencia a esos tipos de mundos es lo más adecuado y más cuando estamos acostumbrados a usar términos en inglés para referirnos a muchas cosas, "crasfeto", "casteo", "dropeo". De todos modos hice una consulta en un grupo de FB a ver que votaban por allá y con eso revertir el cambio si es el caso, dejando todos los nombres de los mundos en español.

**Comment by mora145** [comment]
El texto no hay tanto problema de formato, debido a que son backstories; textos largos. Es más antes había una medicina muy conocida nombrada al final "Mundo Brillante". Si, estoy de acuerdo, falta algo mas de lore al respecto. Solo se conocen un poco por esto, las backstories. 
Al respecto de los nombres "airbag, pack, etc" no son nombres propios... cuentan con traducción; lo que pasa es si te pones a ver, en sí mismos ya son conocidos, pero eso no quiere decir que todo el que los lea los entenderá; lo correcto es traducirlos (Bolsa de aire, mochila cohete). En nuestro caso son palabras menos conocidas, pero perfectamente traducibles y la mayoría de los chicos no creo que las conozca sin investigarlas primero. 

Bien, esperemos la comunidad nos eche una mano con esto.

**Comment by mora145** [comment]
Ya he subido los cambios al respecto de "glitterworlds". 
Falta saber qué piensa la comunidad de cambiar Rimworld por alguna traducción o si prefieren dejarlo tal cual.

**Comment by Zakees** [comment]
Se han hecho los cambios por decisión de un solo traductor? Me consta que no todos están de acuerdo con el cambio, sumado a que las votaciones no han sido precisamente unilaterales.
En el Discord de Facción Latina la mayoría es de más del doble para la versión original con respecto a la traducción literal qué propones.

**Comment by Andres6936** [comment]
¿Es cierto lo que dice @Zakees ? @mora145  @zerstrick

**Comment by Andres6936** [comment]
@Zakees ¿Tienes una foto captura de las votaciones? Es importante ir de acuerdo con la comunidad y me parece apropiado ver los argumentos tanto de los traductores como de los jugadores.

**Comment by mora145** [comment]
@Zakees @Andres6936 Saludos. Me baso en la encuesta que el amigo @zerstrick realizó en el grupo de fb. Si lo desean, pueden pasarse por alla y dar sus opiniones. Si la votación rebasa la cantidad de gente que no quiere el cambio, no hay problema se revierte el cambio. Igual aquí se invitó a los demás traductores a dejar sus opiniones en este tema, pero por lo visto no han opinado por esta via.

**Comment by Zakees** [comment]
El mismo Zerstrick hizo una encuesta en su Discord de Faccion Latina y salió algo distinto. 
![image](https://user-images.githubusercontent.com/34398559/112738650-216a1000-8f65-11eb-97b7-026cf388fc0b.png)
Si le sumamos estas cantidades, a las del Facebook, gana Glitterworld por 4 votos en total. 

Además, hay otra encuesta realizada en facebook (que no sé si eres tú) que gana por mucho el mantener Rimworld y no cambiarlo.

Solo lo comento, en mi traducción si que está todo traducido pero creo que para que las cosas fluyan se deben poner de acuerdo todos los traductores en activo en caso de cambios tan intrusivos.

Un saludo a todos :D

**Comment by mora145** [comment]
![image](https://user-images.githubusercontent.com/25883820/112738825-ee138b00-8f3c-11eb-91dc-bcb5823e666b.png)

Opino que debería llevar traducción. Cuando traduje las backstories por completo, lo había puesto como "Mundo Brillante" en ese momento todos estuvimos de acuerdo en eso, y la traducción gustó a la comunidad. Luego, creo que @zerstrick hizo el cambio, la verdad no sé a quien se consultó, pues en este reposorio no ví notificación ni nada al respecto así fue que se cambió al ingles.

**Comment by Andres6936** [comment]
**¿Cuál es la conclusión?.**

¿Dejar la traducciones intactas (Esto es: Mundo Border, Mundos Brillantes, etc ...)?
¿Revertir cambios y usar la frase original del inglés (Glitterworld, Rimworld, etc ...)?

**Comment by zerstrick** [comment]
Hola @Andres6936 si se lees toda la discusión acerca de este tema, yo inicié una votación, se hizo a la par tanto en el Discord  como en el FB el mismo día(puedes ver las fechas en la imagen adjuntada por @Zakees, ya yo había consultado antes en discord pero se hizo nuevamente )  para tratar de llegar a la mayor cantidad de personas posibles porque la mayoría de las personas del discord no están en el FB o viceversa, invité a @mora145 a que se uniera al Discord para que se hablara allá también del tema, pero no lo hizo, respeto sus razones, también dije que de resultar ganadora una opción YO mismo cambiaria la traducción de ser necesario. Sin embargo al sumar ambas encuestas dejar los nombres en inglés era la ganadora, no se dio un límite de tiempo en FB para las votaciones en discord sí, se dijo que hoy terminaba la encuesta, mi idea era pasarle la foto a mora para que viera el resultado y sumara junto a la del FB pero mucho antes de yo hacer eso ya se había hecho el cambio en el repositorio, yo en vista de eso y de que tampoco me escribió para decirme "mira ve que ya ganó tal opción" y así yo hacer lo que me había comprometido a hacer de darse ese resultado(que no se dio) donde dije que YO mismo iba hacer el cambio. Entonces le escribí en el mismo post de la encuesta de FB diciendo que abandono la traducción, yo no quiero conflictos, sino se va a tomar en cuenta la comunidad que poco a poco se esta construyendo en el discord donde no solo se sube también la traducción oficial latina con un método de instalación bastante sencillo que yo implementé para todos, también se trabaja en la traducción de los mods, prefiero mejor no seguir trabajando en la traducción oficial latina.

**Comment by Andres6936** [comment]
Entiendo tus razones @zerstrick , tu trabajo ha sido impecable todo este tiempo y tus traducciones han sido las únicas que ha recibido la traducción oficial durante meses, es melancólico escuchar tu resolución de abandonar el proyecto, sinceramente, deseo que te quedes, claramente con la imposición de cumplir el resultado de la encuesta que iniciaste.

**Resolución final: Las traducciones de _'Nombres de mundos'_ deben de ser revertidas.**

**Comment by mora145** [comment]
@zerstrick La encuesta que planteaste no tenía fecha límite, por tal motivo y viendo sólo lo resultados de fb, hice los cambios, en pro de las mejoras que estaba/estoy haciendo. No preferí Discord en este caso, porque no todos los que están aquí lo manejan al igual que la mayoría de la comunidad no está presente en esa vía. No sabía que estabas haciendo actualmente otra encuesta por allá. Igualmente es triste tu decisión de abandonar por algo tan simple. De todas formas, si es definitiva me encargaré de seguir dando soporte a esta.

@Andres6936 Pienso que la encuesta debe hacerse en un solo lugar, porque la mayor parte de la comunidad, sin incluir a los traductores prefieren el cambio a su traducción, no de todos los término, sino de al menos este. De todas maneras si la conclusión es irreversible, dejó sin efecto el cambio.

**Comment by mora145** [comment]
![image](https://user-images.githubusercontent.com/25883820/112741722-13f95980-8f56-11eb-9da6-e04898aaa1b5.png)

Por otro lado, está este término también. Deberemos debatir, junto con todos los otros nombres que faltan para los "tipos de mundos"

**Comment by Andres6936** [comment]
@mora Me gusta, coqueteo con entusiasmo la idea de diseñar una nueva encuesta para cada termino, donde se ponga en conocimiento la intención de traducir el original, así decidiremos cual es más agradable a los jugadores.

**Comment by mora145** [comment]
@Andres6936 Estoy de acuerdo. Si el compañero @zerstrick no tiene problema, crearé una encuesta externa a fb y discord, donde todos puedan participar usando un mismo link. 
Una primera encuesta con 3 opciones: **No cambiar nada de la traducción, traducción parcial de los términos y traducción total de los términos.**
Luego dependiendo de los resultados, podremos seleccionar lo que se va a no se va a traducir, dependiendo de la comunidad.

**Comment by zerstrick** [comment]
El debate de los tipos de mundo en lo particular con glitterworld y mundo brillante en lo personal me iba a indicar si cambiaba el nombre de todos ellos, es decir la opción ganadora era para saber si todos se colocaban en inglés o si todos pasaban al español, quizás la segunda encuesta que hubiera hecho yo solo sería para determinar que nombre iba a poner para traducir rimworld si la opción ganadora era eapañol, y no tener una mezclas de nombres inglés, español. La comunidad de rimworld juega su juego  70% - 30% ( inglés y  español) esto es porque juegan con mods, los cuales en su mayoría no tienen traducción, llega un punto donde ellos no saben realmente de dónde sale cada texto, son muy pocos los que juegan meramente el juego vanilla. Así que no veo necesidad de consultar por cada nombre, creo que ya como traductor puedes tomar esa decisión por ellos, con el resto de esos nombres, y solo con glitterworld y rimworld era donde se puede abrir el debate, pero si ya van a colocar los nombres en español entonces solo haz una última encuesta para saber si será "mundo del borde" "mundo limítrofe" "mundo fronterizo" u otras opciones que crean más adecuada y no preguntar por cada nombre.

**Comment by mora145** [comment]
@zerstrick No creo que sea problema una traducción parcial. Por ejemplo, los chicos del fb prefieren "rimworld" para las oraciones, pero "mundo contemporáneo" para "midworld". Supongo que tiene que ver con lo habituados que están con el término, y qué tanto conocen el significado. Como dices, la traducción no está al 100% en español, y creo que es lo mejor; pero ciertos términos es bueno traducirlos, ya que son poco conocidos y sus traducciones no quedan tan mal. De allí toda la conversa que tenemos.
_Entonces de ser definitiva tu salida del proyecto_, tendré que hacer algunas encuestas generales, y dependiendo de lo que salga ir cambiando eso en pro de hacer mas entendible el lore de los mundos. 
Saludos.

**Comment by zerstrick** [comment]
Claro, yo ya no haré preguntas ni del lore u otros asuntos referentes a la traducción, si consigo algún error de ortografía haré los cambios porque eso es algo que nos afecta a todos, pero en lo personal, no me gusta llevar una traducción donde el lore propio tenga nombres mezclados, mi postura en eso es bastante cerrada, si el lore de los mundos es en inglés que todos sean en inglés o si el lore es en español que todo sea en español hablando en este caso concreto de los "Mundos" entonces al no tener que opinar en ese tema creo que puedes hacer las encuestas que consideres necesarias para la traducción. Por lo menos sé que no me estoy yendo con una traducción a medio terminar porque al día de hoy es una de las más completas que hay en este repositorio sumando que nuestro idioma es bastante complejo de traducir con la estructura en que se generan las palabras en RW. Así que si vas a seguir dándole soporte te deseo todo el éxito del mundo.

**Comment by mora145** [comment]
@zerstrick Entiendo tu punto. Igual se te agradece el apoyo al respecto y se te aplaude todo lo que has hecho y seguirás haciendo. De igual modo una disculpa por cualquier malentendido que pueda haber surgido por mi parte. Estoy abierto a mejorar todo lo que pueda sin dejar de lado a nadie ni usurpar nada. Saludos.

**Comment by mora145** [comment]
Bien, he creado la votación. Es ajena a fb y Discord, por lo que deberíamos obtener un resultado más general. Si no hay problema con esto, la promocionaré por fb, y también quedará por esta vía. Se puede cerrar el día viernes, 2 de abril (si no se han realizado más votaciones ese día)

Si la opción parcial o la completa resulta con más votos, tendré que hacer un formulario entero con todos los términos, y varias opciones para que se puedan elegir los mejores

[Votación "Nombres de Mundos"](https://docs.google.com/forms/d/1HeUFD5ruW7DXhpcC9gfRO2jdCgNcF7huBMEcmIOamj4)

Denme el visto bueno, y se inicia el proceso.

**Comment by mora145** [comment]
@Andres6936 Muy bien. Listo, creo que ya quedó.

**Comment by mora145** [comment]
@Andres6936 Agregué al final unas opciones de verificación. 
@zerstrick ¿Eres tan amable de publicarla en Discord? Gracias de antemano.

**Comment by Artorias-Latin** [comment]
@mora145  Buenas, disculpa mi atrevimiento, soy Artorias, el administrador del discord y socio de Zerstrick, quisiera dar una pequeña observación, pienso yo que la propuesta que nos presentas detrás de ella hay un gran trabajo, esto es debido a los cambios que se darían en los archivos, rulespack, stories, etc . Aunque bueno sé que fuiste uno de los pioneros en la traducción del juego, por lo que no me tengo que alargar mucho en explicar, dicho esto, supongo que sabrás de ante mano que cambiar, actualizar, quitar o agregar algo a la traducción lleva su tiempo, esfuerzo y dedicación, sumando también el aumento de trabajo en el proyecto que Zerstrick y yo creamos, traducir mods, cualquier cambio, aunque sea mínimo, también se aplica a los mods, por ejemplo Vikings si no mal recuerdo agrega nuevas historias, que éstas se encuentran los nombres en inglés de los mundos, en fin, es una observación de una falla que encuentro que presenta la propuesta, que si, entiendo tu punto, a cerca de los nombres, pero es un cambio que considero, por lo menos yo, que es demasiado brusco para una traducción que ya está lo bastantemente avanzado como la nuestra, Español Latino. solo lo atrasaría y se acumularía el trabajo. Espero expresarme de la mejor manera posible y que no haya ningún inconveniente al respecto, gracias.

**Comment by mora145** [comment]
@Artorias-Latin 
Saludos. Un gusto conocerte. 

Si, la verdad es así. Cuando se mueve algo en la traducción original, repercute en todo lo demás. 
Cuando hice el cambio de glitterworlds, usé el Notepad++ con una búsqueda general. Por mi parte uso el desktop de GitHub, ya que me permite tener los archivos en mi pc y editarlos localmente, una vez hechos los cambios, lanzo el pull al juego. Lo bueno es que estos término no tienen gran presencia en las rules, sino más que todo en las backstories y unas que otras descripciones. 
Si se utilizan esas vías los cambios pueden ser rápidos.

El punto negativo de dejar sin traducción, obviamente es el desconocimiento por parte de la comunidad de esta parte del lore. Una gran parte de la comunidad conocen muy poco el ingles y estas palabras al ser compuestas, dificultan más su comprensión.

La votación está en curso, y justo ahora está por delante la traducción parcial, a un voto. Siendo la opción de traducción más ligera, solo tendríamos que hacer algunos pequeños cambios, y no precisamente cambiar toda la traducción, con todos los términos.

¿Que propones al respecto?

**Comment by mora145** [comment]
Acabo de revertir los cambios que hice, en pro de seguir la traducción de forma normal, hasta que se tome una decisión definitiva al respecto.

**Comment by Artorias-Latin** [comment]
@mora145 De hecho si, en caso de que se de la traducción para los mundos, se asignara un pequeño grupo, de 2 personas por lo menos en la que éstos se encargarían exclusivamente de traducir y actualizar los nombres, así no habría conflicto ni interrupción en lo absoluto alguno con el proyecto principal, mi preocupación es el posible conflicto que haya con el trabajo que se está haciendo, pero lo importante es debatir y buscar soluciones ante la problemática.

**Comment by mora145** [comment]
> @mora145 Bueno Brother son detalles, y entiendo tu punto de vista, la cuestión es que esas palabras en inglés ya tienen un tiempo sin traducirse por lo cual ya la gente sabe lo que significa cada cosa, es como dice Zerstrick, hay cosas que no se pueden traducir o que no hay una manera precisa de traducir, como la servo-armadura y sus componentes por ejemplo. De hecho si tengo una propuesta y muchas gracias por considerar, en caso de que se de la traducción para los mundos, se asigna un pequeño grupo, de 2 personas por lo menos en la que éstos se encargarían exclusivamente de traducir y actualizar los nombres, así no habría conflicto ni interrupción en lo absoluto alguno con el proyecto principal, mi preocupación es el posible conflicto que haya con el trabajo que se está haciendo, pero lo importante es debatir y buscar soluciones ante la problemática.

Originalmente estos términos habían sido traducidos, y todo estaba adaptado para ellos, el cambio no es tan antiguo, es reciente. Recuerda que esta traducción viene de una casi copia de la traducción Español españa, que luego fue adaptada y traducida; por eso en español españa puedes encontrar los términos originales traducidos.
Por supuesto. Si, puede hacer de a dos personas. Igual dependiendo de qué opción quede como predilecta, tendremos que elegir luego que traducir y qué no.

**Comment by mora145** [comment]
Saludos amigos. Bueno, la encuesta se dá por concluida. Lastimosamente casi nadie de facebook votó, los cuales en su mayoría preferían una traducción parcial. 
Solo queda revisar los votos. Publicaré los resultados directo del archivo que genera el formulario. Cada quien puede revisarse. A excepción de un usuario que votó 2 veces, solo quedaría entonces verificar los demas votos. 
![image](https://user-images.githubusercontent.com/25883820/113507084-6e765500-9516-11eb-9551-4a6d520a951b.png)
![image](https://user-images.githubusercontent.com/25883820/113507159-cb720b00-9516-11eb-8daa-12f280769254.png)

De una u otra forma, más adelante publicaré vía fb un parche con una traducción parcial que los que quieran puedan aplicar, y tener esa traducción parcial que se busca.

**Comment by mora145** [comment]
https://docs.google.com/spreadsheets/d/1sU8Le-zvNGhlDMvmqHfIAftpSc9BFRGv6-VF15lE-NQ/edit?usp=sharing

Link con los resultados.

**Comment by mora145** [comment]
Saludos amigos. 
Hoy fue que pude hablar con el admin del grupo de fb, y pedí que se fijara la encuesta para que hay mas participación de la comunidad de allá. Esperaré hoy a ver que tal va la participación; si no resulta de mucha mas, entonces cerraré la votación.

![image](https://user-images.githubusercontent.com/25883820/113507394-1d676080-9518-11eb-99e1-810c15dd50b4.png)

**Comment by mora145** [comment]
Bueno amigos, este es el resultado final. Aunque hubo poca participación de la gente de facebook, ya no se puede hacer más. 
https://docs.google.com/forms/d/e/1FAIpQLSer7H-EO1tzdyLXOzssNOMKNR2054LwIbyl7aJ8GG8SKoKYeg/viewanalytics

Se le resta un voto a la opción "Sin traducción" debido a que uno de los votantes lo hizo dos veces.

**Comment by zerstrick** [comment]
He tenido problemas con mi proveedor de internet (ABA) poder abrir github cuesta un mundo, yo me imaginé que la gente del facebook no iba a votar mucho, tampoco hice mucha campaña como en la anterior encuesta con las personas que están en el discord pero si sé que son más activos. Yo he participado en la traducción de otros juegos y lo que he aprendido es que las personas se terminan acostumbrando a los nombres que uno elija, recientemente en la traducción de un mod de Oxygen Not Included, cambié el nombre de un recursos Fango por Limo, el mod tiene más de 12 mil suscriptores y nadie emitió ninguna opinión, yo pensé que por tener desde siempre en esa traducción el nombre de fango alguien iba a decir algo y ya tenia una explicación preparada para darla y el porque, pero eso me demostró que muchos solo quieren jugar y no ven muchos detalles que nosotros como traductores si vemos... Sé que el cambio de nombre de mundos choca con la traducción hecha anteriormente, pero como expliqué antes y en mi opinión muy personal, para conservar el nombre Rimworld en muchas partes del juego, los demás mundos con nombres unidos deben cumplir el mismo estándar.

**Comment by mora145** [comment]
Estoy de acuerdo contigo. Yo por mi parte si preferiría traducirlo, a la larga son términos que pueden aportar algo más de luz al lore del juego y lamentablemente la mayor parte de la comunidad no posee casi ningún conocimiento de inglés, más allá de la jerga popular. Pero bueno, el tema ya estaría cerrado al respecto.
Igualmente, estaré por estos lados revisando la traducción y buscando mejorar lo que ya se tiene. 
Saludos.
